package com.example.sondrehj.familymedicinereminderclient.models;

import java.io.Serializable;

/**
 * A model for representing a user with the fields userId and alias. The alias is user specified,
 * while the userId is generated by the server. A user is passed as an argument when sync is
 * initialized, and is mainly used when the user is syncing their own data or their linked
 * user's data.
 */
public class User2 implements Serializable {

    String userId; //6 digit alphanumerical
    String alias;

    public User2(String userId, String alias){
        this.userId = userId;
        this.alias = alias;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String toString(){
        return "UserID: " + getUserId() + " | Alias: " + getAlias();
    }

}



